
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTDIVnonassocPOWCOMMENT DIV EOL ERROR EXPONENT LT_BR MINUS MOD MULT NUM PLUS POW RT_BR\n    calc : exp\n         | empty\n    \n    empty :\n    \n    exp  :    NUM                         \n            | MINUS NUM                 \n            | MINUS LT_BR exp RT_BR     \n            | LT_BR exp RT_BR           \n    \n    exp : exp PLUS exp      \n    \n    exp : exp MINUS exp \n    \n    exp : exp POW exponent          \n\n    \n    exp : exp MULT exp \n    \n    exp : exp DIV exp\n    \n    exponent    : NUM                         \n                | MINUS NUM                 \n                | MINUS LT_BR exponent RT_BR     \n                | LT_BR exponent RT_BR           \n    \n    exponent : exponent PLUS exponent      \n    \n    exponent : exponent MINUS exponent \n    \n    exponent : exponent MULT exponent \n    \n    exponent : exponent DIV exponent\n    '
    
_lr_action_items = {'NUM':([0,5,6,7,8,9,10,11,13,19,20,25,26,27,28,30,],[4,12,4,4,4,18,4,4,4,29,18,18,18,18,18,18,]),'MINUS':([0,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[5,8,-4,5,5,5,19,5,5,-5,5,8,-8,-9,-10,-13,19,-11,-12,8,-7,19,19,19,19,-14,19,26,-6,-17,-18,-19,-20,26,-16,-15,]),'LT_BR':([0,5,6,7,8,9,10,11,13,19,20,25,26,27,28,30,],[6,13,6,6,6,20,6,6,6,30,20,20,20,20,20,20,]),'$end':([0,1,2,3,4,12,15,16,17,18,21,22,24,29,32,33,34,35,36,38,39,],[-3,0,-1,-2,-4,-5,-8,-9,-10,-13,-11,-12,-7,-14,-6,-17,-18,-19,-20,-16,-15,]),'PLUS':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[7,-4,-5,7,-8,-9,-10,-13,-11,-12,7,-7,-14,25,-6,-17,-18,-19,-20,25,-16,-15,]),'POW':([2,4,12,14,15,16,17,18,21,22,23,24,29,32,33,34,35,36,38,39,],[9,-4,-5,9,9,9,-10,-13,9,9,9,-7,-14,-6,-17,-18,-19,-20,-16,-15,]),'MULT':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[10,-4,-5,10,10,10,-10,-13,-11,-12,10,-7,-14,27,-6,27,27,-19,-20,27,-16,-15,]),'DIV':([2,4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[11,-4,-5,11,11,11,-10,-13,-11,-12,11,-7,-14,28,-6,28,28,-19,-20,28,-16,-15,]),'RT_BR':([4,12,14,15,16,17,18,21,22,23,24,29,31,32,33,34,35,36,37,38,39,],[-4,-5,24,-8,-9,-10,-13,-11,-12,32,-7,-14,38,-6,-17,-18,-19,-20,39,-16,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,6,7,8,10,11,13,],[2,14,15,16,21,22,23,]),'empty':([0,],[3,]),'exponent':([9,20,25,26,27,28,30,],[17,31,33,34,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','calc.py',115),
  ('calc -> empty','calc',1,'p_calc','calc.py',116),
  ('empty -> <empty>','empty',0,'p_empty','calc.py',150),
  ('exp -> NUM','exp',1,'p_factor','calc.py',156),
  ('exp -> MINUS NUM','exp',2,'p_factor','calc.py',157),
  ('exp -> MINUS LT_BR exp RT_BR','exp',4,'p_factor','calc.py',158),
  ('exp -> LT_BR exp RT_BR','exp',3,'p_factor','calc.py',159),
  ('exp -> exp PLUS exp','exp',3,'p_expPLUS','calc.py',179),
  ('exp -> exp MINUS exp','exp',3,'p_expMINUS','calc.py',190),
  ('exp -> exp POW exponent','exp',3,'p_expPOW','calc.py',198),
  ('exp -> exp MULT exp','exp',3,'p_expMULT','calc.py',208),
  ('exp -> exp DIV exp','exp',3,'p_expDIV','calc.py',216),
  ('exponent -> NUM','exponent',1,'p_factorexponent','calc.py',234),
  ('exponent -> MINUS NUM','exponent',2,'p_factorexponent','calc.py',235),
  ('exponent -> MINUS LT_BR exponent RT_BR','exponent',4,'p_factorexponent','calc.py',236),
  ('exponent -> LT_BR exponent RT_BR','exponent',3,'p_factorexponent','calc.py',237),
  ('exponent -> exponent PLUS exponent','exponent',3,'p_expPLUSexponent','calc.py',257),
  ('exponent -> exponent MINUS exponent','exponent',3,'p_expMINUSexponent','calc.py',268),
  ('exponent -> exponent MULT exponent','exponent',3,'p_expMULTexponent','calc.py',276),
  ('exponent -> exponent DIV exponent','exponent',3,'p_expDIVexponent','calc.py',284),
]
